from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class QueryResult(Protocol):
    data: list[dict[str, Any]]


@runtime_checkable
class TableQuery(Protocol):
    def select(self, columns: str = "*") -> "TableQuery": ...

    def eq(self, column: str, value: Any) -> "TableQuery": ...

    def order(self, column: str, *, desc: bool = False) -> "TableQuery": ...

    def limit(self, value: int) -> "TableQuery": ...

    def insert(self, payload: Any) -> "TableQuery": ...

    def update(self, payload: dict[str, Any]) -> "TableQuery": ...

    def delete(self) -> "TableQuery": ...

    def upsert(self, payload: Any, *, on_conflict: str | None = None) -> "TableQuery": ...

    def execute(self) -> QueryResult: ...


@runtime_checkable
class DatabaseTable(Protocol):
    def select(self, columns: str = "*") -> TableQuery: ...

    def insert(self, payload: Any) -> TableQuery: ...

    def update(self, payload: dict[str, Any]) -> TableQuery: ...

    def delete(self) -> TableQuery: ...

    def upsert(self, payload: Any, *, on_conflict: str | None = None) -> TableQuery: ...


@runtime_checkable
class DatabaseClient(Protocol):
    def table(self, name: str) -> DatabaseTable: ...
